config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "welcome#about"
  
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create" 
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify


  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.deck = Array.new(6) { 'B' } + Array.new(11) { 'R' }
    @chatroom.deck.shuffle!
    @chatroom.roles = %w{Liberal Liberal Liberal Fascist Hitler}
    @chatroom.roles.shuffle!
    @chatroom.fasboard = %w{nothing nothing peek shot shot end}
    @chatroom.started = false
    @chatroom.faspolicies = 0
    @chatroom.libpolicies = 0
    @chatroom.discard = []
    @chatroom.players = []
    @chatroom.ended = false
    @chatroom.draw = []
    @chatroom.votes = Array.new(5) { '' }
    @chatroom.president = 1
    @chatroom.chancellor = 1
    @chatroom.tracker = 0
    @chatroom.prescut = -1
    @chatroom.chanccut = -1
    @chatroom.needsvotes = false

    p @chatroom.to_json

    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">topic:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  <div id="chatroom-errors">
    
  </div>
    <ul id="chatroom-index"> 
  <% if @chatrooms.any? %>
      <%= render @chatrooms%>
  <%else %>
    </ul>
    <p>Be the first one to make a chatroom!</p>
  <% end %>
</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Create a Chatroom on a programming topic</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">topic:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/chatrooms/show.html.erb
<div class="panel panel-default tracks-container sixteen wide column">
  <section class="tracks">
    <div class="track-flipper track-flipper-top flipped">
      <div class="track top-track-front"></div>
      <div class="track top-track-back"></div>
    </div>
    <section class="enactedpolicies-container">
    </section>
    <div class="track-flipper track-flipper-bottom flipped">
      <div class="track bottom-track-front"></div>
      <div class="track bottom-track-back track0"></div>
    </div>
    <div class="electiontracker fail0" id="tracker"></div>
  </section>
</div>

<div style="position:absolute;right: 5%!important; width: 40vw;display:inline; margin-top: -25%;">
  <h1><%= @chatroom.topic %></h1>

  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: @chatroom.messages, locals: {:game => @chatroom} %>
      </div>
    <% else %>
      <div class="panel-body hidden" id="messages">
      </div>
    <% end %>
  </div>

  <script>
      const user = "<%= current_user.username %>";
      const out = document.getElementById("messages");
      let isScrolledToBottom;
      out.scrollTop = out.scrollHeight - out.clientHeight;
      setInterval(function () {
          isScrolledToBottom = out.scrollHeight - out.clientHeight <= out.scrollTop + 1;

          if (isScrolledToBottom)
              out.scrollTop = out.scrollHeight - out.clientHeight;
      }, 500);

      <% if @chatroom.started %>
      const role = "<%= @chatroom.roles[@chatroom.players.index current_user.username].html_safe %>";

      $("#messages").removeClass('hidden');
      $("#messages").append(`<p class='system'>Your secret role is ${role}.</p>`);

      <% if %w{Fascist Hitler}.include? @chatroom.roles[@chatroom.players.index current_user.username] %>
      const teammate = "<%= @chatroom.players[@chatroom.roles.index (%w{Fascist Hitler} - [@chatroom.roles[@chatroom.players.index current_user.username]])[0]] %>";
      const tr = "<%= (%w{Fascist Hitler} - [@chatroom.roles[@chatroom.players.index current_user.username]])[0].html_safe %>";
      $("#messages").removeClass('hidden');
      $("#messages").append(`<p class='system'>Your teammate is ${teammate} (${tr}).</p>`);
      <% end %>
      const lp = <%= @chatroom.libpolicies %>;
      const fp = <%= @chatroom.faspolicies %>;

      for (let i = 0; i < lp; i++) {
          $(".enactedpolicies-container").append(`<div class="enactedpolicies-card-container flippedY inplace liberal${i + 1}">
        <div class="enactedpolicies-card front"></div>
        <div class="enactedpolicies-card back liberal"></div>
      </div>`);
      }

      for (let i = 0; i < fp; i++) {
          $(".enactedpolicies-container").append(`<div class="enactedpolicies-card-container flippedY inplace fascist${i + 1}">
        <div class="enactedpolicies-card front"></div>
        <div class="enactedpolicies-card back fascist"></div>
      </div>`);
      }
      <% end %>
  </script>


  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom} %>
</div>