config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "welcome#about"
  
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create" 
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Secret Hitler", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <% if current_user %>
   <li>
    <%= link_to "new game", new_chatroom_path%>
   </li>
  <% end %>
  
  <li>
    <%= link_to "games", chatrooms_path %>
  </li> 
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li>
      <%= link_to "Log Out", logout_path, method: "delete" %>
    </li>
  <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Log In", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secret Hitler</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css"/>
</head>

<body>
<%= render partial: 'layouts/navbar' %>

<div class="container_">
  <%= yield %>
</div>
</body>
</html>